%YAML:1.0
---

# ------------------------------------------------------------------
# 必须指定的参数


# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓网络相关参数↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
# 训练脚本路径
train_script_path: /root/Codes/NBNet-Demo/Network/train_mge.py
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑网络相关参数↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑


# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓输入相关参数↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
# 输入影像类型，用于指定是否为raw图，默认为raw，如果不是换成normal
img_mode: raw

# 影像彩色顺序，默认为rgb，如果不是换成bgr
color_mode: rgb

# 输入噪声影像所在文件夹
input_img_dir: /root/Codes/NBNet-Demo/Datasets/input

# 输入噪声影像文件格式
input_img_type: CR3

# 输入真值影像所在文件夹
gt_img_dir: /root/Codes/NBNet-Demo/Datasets/gt

# 真值影像文件格式
gt_img_type: CR3
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑输入相关参数↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑


# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓输出相关参数↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
# 输出影像块的文件夹
block_img_dir: /root/Codes/NBNet-Demo/Datasets/dataset

# 输出影像块的文件格式
block_img_type: png
# ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑输出相关参数↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

# ------------------------------------------------------------------


# ------------------------------------------------------------------
# 可选的参数

# 分割影像块的大小，建议2的次方倍
block_size: 256

# 影像块个数（最终会进行增强，数量会增加4倍）
block_num: 500

# 验证数据占比
vali_rate: 0.1

# Epoch数
epoch_num: 50

# 每个Epoch中的step数
step_num: 200

# batch size
batch_size: 32

# ------------------------------------------------------------------
